/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package  projet_youtube_produit;

import BDD.Parameter;
import BDD.ResultSetTableModel;
import BDD.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author liamsi
 */
public class cachier extends javax.swing.JFrame {

    /**
     * Creates new form cachier
     */
    
    ResultSet rs;
    db_connection db;
    int old, dec, now;
    public cachier() {
        db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        
        initComponents();
        table();
        jam();
    }

    public void table() {
        String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
        rs = db.querySelect(colon, "produit");
        tbl_res.setModel(new ResultSetTableModel(rs));
    }

    public void importer() {
        String colon[] = {"num_facture","code_produit","reference","prix_vente","stock_sortie","subtotal"};
        rs = db.fcSelectCommand(colon, "vente", "num_facture='" + txtfac.getText() + "'");
        tbl_ven.setModel(new ResultSetTableModel(rs));
    }
     public void jam() {
        Date s = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
        SimpleDateFormat jam = new SimpleDateFormat("HH:mm");
        lbl1.setText(jam.format(s));
        lbl2.setText(tgl.format(s));}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_res = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comrech = new javax.swing.JComboBox();
        txtrech = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtref = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtran = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfou = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtrem = new javax.swing.JTextField();
        txtnou = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtsto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lbltot1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtfac = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ven = new javax.swing.JTable();
        lbltot2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtcas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1029, 745));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("resultat");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 10, 100, 24);

        tbl_res.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "code_produit", "reference", "deseignation", "rangement", "fournisseur", "remise", "prix", "stock "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_res.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_resMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_res);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 990, 90);

        jButton7.setText("actualiser");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(840, 0, 80, 20);

        jButton8.setText("sortire");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(920, 0, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 990, 140);

        jPanel2.setBackground(new java.awt.Color(239, 252, 253));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("recherche par catégorie :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 0, 250, 20);

        comrech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "code_produit", "reference", "deseignation", "rangement", "fournisseur", "remise", "prix", "stock" }));
        jPanel2.add(comrech);
        comrech.setBounds(50, 30, 240, 30);
        jPanel2.add(txtrech);
        txtrech.setBounds(150, 70, 180, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("code_produit :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 130, 100, 17);

        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });
        jPanel2.add(txtcod);
        txtcod.setBounds(150, 120, 160, 30);

        txtref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrefActionPerformed(evt);
            }
        });
        jPanel2.add(txtref);
        txtref.setBounds(150, 160, 160, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("reference     :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 170, 100, 17);

        txtran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtranActionPerformed(evt);
            }
        });
        jPanel2.add(txtran);
        txtran.setBounds(150, 200, 160, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Prix        :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 290, 100, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("rangement :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 210, 100, 17);

        txtfou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfouActionPerformed(evt);
            }
        });
        jPanel2.add(txtfou);
        txtfou.setBounds(150, 240, 160, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("fournisseur :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 250, 100, 17);

        txtpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriActionPerformed(evt);
            }
        });
        jPanel2.add(txtpri);
        txtpri.setBounds(150, 280, 160, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("remise     :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 340, 100, 17);

        txtrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremActionPerformed(evt);
            }
        });
        jPanel2.add(txtrem);
        txtrem.setBounds(150, 330, 160, 30);

        txtnou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnouActionPerformed(evt);
            }
        });
        jPanel2.add(txtnou);
        txtnou.setBounds(150, 370, 160, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("nouveau Prix  :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 380, 100, 17);

        txtsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstoActionPerformed(evt);
            }
        });
        txtsto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstoKeyReleased(evt);
            }
        });
        jPanel2.add(txtsto);
        txtsto.setBounds(150, 410, 160, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Stock sortire  :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 420, 100, 17);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("Ajouter au vente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(40, 500, 260, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setText("RP : ");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(60, 460, 50, 30);

        lbltot1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbltot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot1.setText("0");
        jPanel2.add(lbltot1);
        lbltot1.setBounds(110, 460, 170, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("recherche ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(10, 70, 133, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 150, 360, 550);

        jPanel3.setBackground(new java.awt.Color(240, 249, 252));
        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Num de facture :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 130, 100, 17);

        txtfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfacActionPerformed(evt);
            }
        });
        jPanel3.add(txtfac);
        txtfac.setBounds(140, 120, 160, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setText("recherche ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(310, 120, 120, 27);

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(440, 120, 110, 27);

        tbl_ven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "Prix de vente", "Stock sortire", "total "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_ven);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 170, 630, 110);

        lbltot2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbltot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot2.setText("0");
        jPanel3.add(lbltot2);
        lbltot2.setBounds(380, 310, 190, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("payé aprés :");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(290, 380, 90, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Rp");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(300, 310, 70, 30);
        jPanel3.add(txtpay);
        txtpay.setBounds(400, 380, 130, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("cash :");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(80, 380, 50, 30);

        txtcas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcasKeyReleased(evt);
            }
        });
        jPanel3.add(txtcas);
        txtcas.setBounds(140, 380, 130, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(140, 440, 350, 30);

        jPanel4.setBackground(new java.awt.Color(253, 230, 250));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setText("Vente");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl1.setText("jLabel12");

        lbl2.setText("jLabel17");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 630, 70);

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Total ");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(160, 310, 110, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setText("annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(140, 480, 350, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(370, 150, 630, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_resMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_resMouseClicked
        txtcod.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 0)));
        txtref.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 1)));
        txtran.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 3)));
        txtfou.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 4)));
        txtrem.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 5)));
        txtpri.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 6)));
       cout();
    }//GEN-LAST:event_tbl_resMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Recu n = new Recu();
        n.setVisible(true);
        payaprés();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed

    private void txtrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrefActionPerformed

    private void txtranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtranActionPerformed

    private void txtfouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfouActionPerformed

    private void txtpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriActionPerformed

    private void txtremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremActionPerformed

    private void txtnouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnouActionPerformed

    private void txtstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstoActionPerformed

    private void txtfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txtrech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP complete le champ de recherche");
        } else {
            if (comrech.getSelectedItem().equals("code_produit")) {
                String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "produit", "code_produit LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("reference")) {
                String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "produit", "reference LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("deseignation")) {
                String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "produit", "deseignation LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(new ResultSetTableModel(rs));
                } else if (comrech.getSelectedItem().equals("rangement")) {
                String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "produit", "rangement LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("fournisseur")) {
                String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "produit", "fournisseur LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(new ResultSetTableModel(rs));
                } else if (comrech.getSelectedItem().equals("remise")) {
                String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "produit", "remise LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("prix")) {
                String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "produit", "prix LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(new ResultSetTableModel(rs));
                } else if (comrech.getSelectedItem().equals("stock")) {
                String colon[] = {"code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "produit", "stock LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(new ResultSetTableModel(rs));
            
            
            
                
            
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtcod.getText().equals("") || txtref.getText().equals("") || txtran.getText().equals("")
                || txtfou.getText().equals("") || txtrem.getText().equals("") || txtpri.getText().equals("") || txtnou.getText().equals("")|| txtsto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer vos donneé");
        } else if (txtfac.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer le num de facture");
        } else {
            String[] colon = {"num_facture","code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"};
            String[] isi = {txtfac.getText(), txtcod.getText(), txtref.getText(), txtnou.getText(), txtsto.getText(), lbltot1.getText()};
            System.out.println(db.queryInsert("vente", colon, isi));
            try {
                if (!test_stock()) { 
                    JOptionPane.showMessageDialog(this, "le stock est Limiter");
                } else {
                    def(); //true
                    table(); //true
                }
            } catch (SQLException ex) {
                Logger.getLogger(cachier.class.getName()).log(Level.SEVERE, null, ex);
                System.err.println("\n"+ex);
            }
            subtotal();
            importer();
            total();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        importer();
        total();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = String.valueOf(tbl_ven.getValueAt(tbl_ven.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "est ce que tu es sure que tu veux supprimer ", "Attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("vente", "id=" + id);
        } else {
            return;
        }
        importer();
        total();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String invoice = txtfac.getText();
        if (JOptionPane.showConfirmDialog(this,"est ce que tu es sure que tu veux supprimer ","attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("vente", "num_facture=" + invoice);
        } else {
            return;
        }
        importer();
        total();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtstoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstoKeyReleased
 subtotal();        // TODO add your handling code here:
    }//GEN-LAST:event_txtstoKeyReleased

    private void txtcasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcasKeyReleased
payaprés();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcasKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     table();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void cout() {
        double a = Double.parseDouble(txtpri.getText());
        double b = Double.parseDouble(txtrem.getText());
        double c = a - a * (b / 100);
        txtnou.setText(String.valueOf(c));
    }
     public void subtotal() {
        double a = Double.parseDouble(txtnou.getText());
        double b = Double.parseDouble(txtsto.getText());
        double c = a * b;
        lbltot1.setText(String.valueOf(c));}
     
      public void total() {
        rs = db.exécutionQuery("SELECT SUM(subtotal) as subtotal FROM vente WHERE num_facture = '" + txtfac.getText() + "'");
        try {
            rs.next();
            lbltot2.setText(rs.getString("subtotal"));
        } catch (SQLException ex) {
            Logger.getLogger(cachier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       public boolean test_stock() throws SQLException {
        boolean teststock;
        rs = db.querySelectAll("produit","code_produit='" + txtcod.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txtsto.getText());
        if (old < dec) {
            teststock = false;
        } else {
            teststock = true;
        }
        return teststock;
    }

    public void def() throws SQLException {
        rs = db.querySelectAll("produit", "code_produit='" + txtcod.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txtsto.getText());
        now = old - dec;
         String nvstock = Integer.toString(now);

        String a = String.valueOf(nvstock);
        String[] colon = {"stock"};
        String[] isi = {a};
        System.out.println(db.queryUpdate("produit", colon, isi, "code_produit='" + txtcod.getText() + "'"));
    }

    public void payaprés() {
        int a = Integer.parseInt(lbltot2.getText());
        int b = Integer.parseInt(txtcas.getText());
        int c = b - a;
        txtpay.setText(Integer.toString(c));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cachier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox comrech;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbl1;
    public static javax.swing.JLabel lbl2;
    public static javax.swing.JLabel lbltot1;
    public static javax.swing.JLabel lbltot2;
    public static javax.swing.JTable tbl_res;
    public static javax.swing.JTable tbl_ven;
    public static javax.swing.JTextField txtcas;
    public static javax.swing.JTextField txtcod;
    public static javax.swing.JTextField txtfac;
    public static javax.swing.JTextField txtfou;
    public static javax.swing.JTextField txtnou;
    public static javax.swing.JTextField txtpay;
    public static javax.swing.JTextField txtpri;
    public static javax.swing.JTextField txtran;
    public static javax.swing.JTextField txtrech;
    public static javax.swing.JTextField txtref;
    public static javax.swing.JTextField txtrem;
    public static javax.swing.JTextField txtsto;
    // End of variables declaration//GEN-END:variables
}
